audit_header: false
title: "Calgary's Best Real Estate Training - Eric Mortimer"
description: Eric Mortimer, a top Real Estate Agent in Calgary, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://ericmortimer.eventbrite.ca/
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Eric Mortimer
  title:
  license_number:
  about_markdown: |
    Eric Mortimer is an award winning real estate agent and Agent of Change. As he says, “sometimes I help people move geographically and sometimes I help people move emotionally, mentally, and spiritually.”

    Being a guide and coaching you expedite your personal and professional success is Eric’s true passion and purpose.

    In addition to being on of Calgary Top Realtors, some of Eric’s background also includes: sharing the stage with a number of our living luminaries, Founder of the Clarity Circle, being a Certified High Performance Coach, turning around two Calgary branch offices for multinational corporations, increasing a number of people’s net and self-worth, hundreds of thousands of video views and more on social media, and marrying an amazing woman that puts up with his sense of humor. He was also just awarded MAN OF THE YEAR by Mentor Discover Inspire, an international organization dedicated to personal growth.
  market: Calgary
  brand: Eric Mortimer & Associates
  brokerage: Maxwell Capital Realty
  address: '#150, 75 Crowfoot Rise, NW Calgary, Alberta T2E 0B8'
  phone: 403-827-8081
  phone_type:
  phone2:
  phone2_type:
  email: Eric@EricMortimer.com
  url: https://calgaryvideoblog.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Eric Mortimer & Associates can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/EricMortimerRealtor/
  linkedin_url: https://www.linkedin.com/in/ericcmortimer/
  youtube_url: https://www.youtube.com/channel/UCQhx0HNyY95NIahfYbXPlIA
  twitter_url: https://twitter.com/EricCMortimer
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Calgary Real Estate Podcast with Eric Mortimer'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Calgary Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Eric Mortimer & Associates - your professional Calgary Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Calgary, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Eric Mortimer'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Calgary Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#eb1c29'
  theme_color: '#313939'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#eb1c29'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
