audit_header: false
title: Calgary's Best Real Estate Training - Eric Mortimer
description: >-
  Eric Mortimer, a top Real Estate Agent in Calgary, shares his own internal
  real estate agent training for free. His Real Estate Training, Tips and Advice
  will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Guaranteed sale
    url: https://mortimer-offer.paperform.co/
  - title: Home Valuation
    url: https://mortimer-value.paperform.co/
  - title: Home Search
    url: https://mortimer-search.paperform.co/
client:
  name: Eric Mortimer
  title:
  license_number:
  about_markdown: >
    Eric Mortimer is an award winning real estate agent and Agent of Change. As
    he says, “sometimes I help people move geographically and sometimes I help
    people move emotionally, mentally, and spiritually.”


    Being a guide and coaching you expedite your personal and professional
    success is Eric’s true passion and purpose.


    In addition to being on of Calgary Top Realtors, some of Eric’s background
    also includes: sharing the stage with a number of our living luminaries,
    Founder of the Clarity Circle, being a Certified High Performance Coach,
    turning around two Calgary branch offices for multinational corporations,
    increasing a number of people’s net and self-worth, hundreds of thousands of
    video views and more on social media, and marrying an amazing woman that
    puts up with his sense of humor. He was also just awarded MAN OF THE YEAR by
    Mentor Discover Inspire, an international organization dedicated to personal
    growth.
  market: Calgary
  brand: Eric Mortimer & Associates
  brokerage: Maxwell Capital Realty
  address: '#150, 75 Crowfoot Rise, NW Calgary, Alberta T2E 0B8'
  phone: 403-827-8081
  phone_type:
  phone2:
  phone2_type:
  email: Eric@EricMortimer.com
  url: https://calgaryvideoblog.com
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: >-
      Let's talk about how Eric Mortimer & Associates can take your business to
      new heights.
    CTA_link_text: Free Strategy Session
    CTA_url: /contact/
hero:
  video:
    enabled: false
    path: /uploads/houses-video.mp4
    use_overlay: true
    overlay-intensity: 0.5
  hero_image: /img/gray.png
  logoimage: /uploads/logo.png
  logoname: Eric Mortimer Logo
  use_overlay: true
  overlay-intensity: 0.5
  hero_tabs:
    enabled: false
    tabs:
      - title: 'Call to Action #1'
        headline: A Benefit-Driven Headlines Goes Here
        subheadline: Write a sentence about what they will get from you.
        button_text: 'CTA Button #1'
        button_link: '#'
      - title: 'Call to Action #2'
        headline: Tell Them The Benefit of Your Offer
        subheadline: Write a sentence about what they will get from you.
        button_text: 'CTA Button #2'
        button_link: '#'
      - title: 'Call to Action #3'
        headline: Capture Their Attention With a Headline
        subheadline: Write a sentence about what they will get from you.
        button_text: 'CTA Button #3'
        button_link: '#'
      - title: 'Call to Action #4'
        headline: Give Them a Great Reason to Respond
        subheadline: Write a sentence about what they will get from you.
        button_text: 'CTA Button #4'
        button_link: '#'
  header: CALGARY REAL ESTATE VIDEO BLOG
  header_color: '#ffffff'
  subheader: >-
    This is where you put a clear description of your primary offer and why they
    should click the call to action button below.
  subheader_color: '#ffffff'
  button_text: 'Call to Action #1'
  button_link: '#'
  show_sidenav_link: true
  show_footer_link: true
  add_button_to_hero: false
blog:
  CTA_main_box_markdown: >-
    **Take one step closer to the home you love.** Use my secure, online loan
    application to jump-start the loan process and lock in a low mortgage rate.
  CTA_main_box_link:
    title: Apply Now
    url: >-
      https://apply.highlandhomeloans.com/jon.knoblock/SPAs/UserLogin/index.html#/userRegistration
  author:
    name: Eric Mortimer
    name_link: mailto:Eric@EricMortimer.com
    image: /uploads/headshot.jpg
    bio: >-
      Your Next Journey STARTS HERE. Along the journey of life come many
      milestones. Eric Mortimer is an expert at helping you make the most of one
      of life’s most important – the sale or purchase of a home. As a leading
      Calgary real estate professional, Eric brings a big-picture perspective to
      your move, weighing the impact on you, your family and your financial
      situation. That’s why he’s able to make your move so successful. Contact
      Eric prior to your next move For a Successful Journey.
  CTA_content_box:
    title_markdown: '**Want to work with me?** Here are some ways to get involved.'
    items:
      - title: Schedule a Call
        url: https://lo.highlandhomeloans.com/jon.knoblock/about/contact-me
        markdown: Have questions about getting a mortgage? **I can help you.**
      - title: Latest Mortgage Insights
        url: https://signup.e2ma.net/signup/1988259/1960765/
        markdown: >-
          **Subscribe now** to get my latest insights and information on what's
          going on in the lending industry.
      - title: Apply Now
        url: >-
          https://apply.highlandhomeloans.com/jon.knoblock/SPAs/UserLogin/index.html#/userRegistration
        markdown: >-
          **Take one step closer to the home you love.&nbsp;**Use my secure,
          online loan application to jump-start the loan process and lock in a
          low mortgage rate.
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/EricMortimerRealtor/
  linkedin_url: https://www.linkedin.com/in/ericcmortimer/
  youtube_url: https://www.youtube.com/channel/UCQhx0HNyY95NIahfYbXPlIA
  twitter_url: https://twitter.com/EricCMortimer
  instagram_url:
  pinterest_url: https://www.pinterest.com/
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://www.podcasts.com/
podcast:
  title: Calgary Real Estate Podcast with Eric Mortimer
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Calgary
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Eric Mortimer & Associates - your
    professional Calgary Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Calgary, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Eric Mortimer
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Calgary Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#eb1c29'
  theme_color: '#313939'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#eb1c29'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
